#ENC[AES256_GCM,data:H2ddBdqaseP02ucVvEeZzoGi/DeFmI33hSq6HqCKIWVb5uzRUd7cKv4sKfhUZHx5gGs=,iv:rI8hh2y5tfgwjAl31pq4y727Kj8BOv6Z8RdS0oGVLWA=,tag:lNfBHdVCltXMZg5SadZJQw==,type:comment]
proxmox_api_host: ENC[AES256_GCM,data:/X1x6W2GLhsP6w==,iv:C/o3BmkEbbZlDxPq98I0KdcAe2tuvNe1GjXOiplGFD4=,tag:yp491KvIyHFJmM82fSfobg==,type:str]
proxmox_node: ENC[AES256_GCM,data:j/a1,iv:IWhJm0y2YrXIk+tiHCQJJkZbQgQ41ub95dMroEBD1oA=,tag:/YHhEIIBTn6LltqyurPRXA==,type:str]
proxmox_storage: ENC[AES256_GCM,data:zGuCE3VOsmun,iv:Pgv8FRm6eMjPBCl9JrbxXRTTqO+sV8qHaX3mZj6Kkl4=,tag:RJwA91JJgfj70cBQNX1BUw==,type:str]
proxmox_bridge: ENC[AES256_GCM,data:7bneBTY=,iv:ILtdFVgQbd+acbCSss5J7Zn7/wV7+oapKmwftRXemJE=,tag:vUXrxDBzg+G9cUA67EyYug==,type:str]
proxmox_vlan_tag: ENC[AES256_GCM,data:DoQ=,iv:5s5+kzev24D0IoQzWaHwUmDsVU+XPvG/NR6hqWQNvB4=,tag:WMhD9N2EHYxhpSa7r4V4hw==,type:int]
proxmox_template_vmid: ENC[AES256_GCM,data:tYLJmg==,iv:UMp9Nh/sIUx2UBv1lMCpttHpSGNWpqfTDdP64QmoH/U=,tag:OC83iEs3yZofMAbyxMUlYA==,type:int]
proxmox_validate_certs: ENC[AES256_GCM,data:m9iWC0Y=,iv:AiqyIBc/ZIhFNrGV5mK+O4yKsVApVsUVFH/YcWaTduE=,tag:4ta5bhgUO0O04kHa1n8nMA==,type:bool]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEt0dUtoUSBHZ2Jj
            Z0x2Y3FsL2JQVUY1SVJRMjQ3bDVydmFQWmNiVDBPbzJIcnJBbTA4CjNhVGpGYkVv
            TjJDaytCaU5MQ3N2ZHp0VkpXWnM0eDdPOGovS0lFeHkyb0kKLS0tIHRKSG5SV0tu
            NGJsMWlEVzd6Y2dNenp3a2R4OWoxY3RpNm8zSnlhZlZjRHcKUu78C+AB7Tppr/cZ
            GZ/UuiFn3rQpHwXYZjk7hVXC3pn9NsBuIT+tOeJ6gX6EpixpGBln6S9SYpGBthDr
            GqvSuA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEVkycfAgl4lqaLLqkClUVlaX/ZiSZ+0l0i6rFtuZx/J sops-control-key
    lastmodified: "2026-10-02T14:37:07Z"
    mac: ENC[AES256_GCM,data:sxcykb+lZaIUP/CfUNBA5v//499eF++LD92EjMSgijKJ99Cob8McC7Gu/OUoovUjc2O3rbmwm0AL+1yLocQ5LC63IArNvJPh1h9JD4w1SAD72/4WN5G6zfUfAgE2mOvtKd3lAWvsis49eDUsAbk3nClS1XKREPI81VXZzaheJQA=,iv:J7F28HNFhQjloZA0Krimh22/aNFSRlrAA0kGErDIYJk=,tag:ptmYGwXENMAeotemCDHQvg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
