#ENC[AES256_GCM,data:OnfjAOmcWEKotshNkqAlY+qexJegfO/gEsCPFNd99g1JNR0dZsXx5tB3fqcdHbhFZJs=,iv:Q2qMWMFHYohrQE7+XjtAFbrhXgtfSEqDobCr9eE0x0w=,tag:8iBrlPtp6wANf/UZqY01lw==,type:comment]
proxmox_api_host: ENC[AES256_GCM,data:bB+LM/Lufyi58A==,iv:TXq8MagpQlKi52Y+/igmv1NC9dsZ055oVTwqu9m2R9A=,tag:NKP/joroHBfHs6JLJtTAlQ==,type:str]
proxmox_node: ENC[AES256_GCM,data:5lH4,iv:xNDS9Zekpk5LAp1Z7TPLgiAFt+xOO7D+aN9F7kQHV5s=,tag:aofI0jawpjTCiQ1UMFwnNQ==,type:str]
proxmox_storage: ENC[AES256_GCM,data:t8dfGbd7GcpW,iv:00LZN5QM2SfaXQeHUhEKQDDhYgL/4h/fvQjDFf3fqLw=,tag:CjT0KyWgvn/3S29VzH+OUw==,type:str]
proxmox_bridge: ENC[AES256_GCM,data:78IkTfg=,iv:v6Hgq+9+Ng3JpAOuq9OpK678mDDduxr0TzUX5TfYCnI=,tag:BfOAQ6kjjuryTVF3Jx07KA==,type:str]
proxmox_vlan_tag: ENC[AES256_GCM,data:+HY=,iv:ShNyCsMcBAcHOTWiNybQJteqZhE7kED7XfVfNqaxf/Q=,tag:SY/TGZ2843Gh2cpbrDsMqA==,type:int]
proxmox_template_vmid: ENC[AES256_GCM,data:1UxILQ==,iv:gS9EIbdB48KEjXiwMb6UvPkiBp/IYjgX8vAIbbYl8zk=,tag:mQ3reFuYntrFe+pr809HrQ==,type:int]
proxmox_validate_certs: ENC[AES256_GCM,data:/xBsAQM=,iv:eepoAyYF12REL18D1NyGPGnC0dDqz9MV5Urpsav2bm4=,tag:O8XsjaboKa0lTUbmxWqwTA==,type:bool]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG5CS1BZdyBBelF6
            ZTZEb2xlL0w5QXhweDE5anRaenNMeHVSaWRWaUZJa29mMjAwS0FZCmZINHp4SjZS
            UU1OYlg1MS9NcEtNMS9Vb2JnNFFQWGhOUjdMUWVDRlQ3ZGcKLS0tIFdaQk5MSVVL
            MFB0VXU5allic1VUMFJXekZpN0JoOE5WMFJpUGE2bzRZOFUKc4MEyNdd56yf2UX0
            aH9JhbnxUpTMT/qSjUb1S7hxDykW7IN+HWg6i1EUmtUHjcdzk4dPowq0GWSh9x0s
            DxjwRQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKFyGuei5gt+jbejZvCrpX0XXD1854N7BkkmEQDRh28/ sops-control-key
    lastmodified: "2026-10-02T14:49:08Z"
    mac: ENC[AES256_GCM,data:LWatHfpD3/R6cvLuWkrKasezkJbCGCx6C7hIk9U/dSApziseizsA1egPNlH68rHIMT5wYQc9OBiGwUN+QJKvLrVR95Alp9IbIUHc38AXLzVMzwlhBIj/i0fuvdZXlr6hu7zNLQcTNsPu/asW/oR1+D2MSWZ1ktCbIQ56jUk6D+s=,iv:1lv9OU3sWkD5o86wF3vlWqKnIiZTyZOhZounwzew0WY=,tag:chQLMcOAqa80EXXBzuXa3Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
