#ENC[AES256_GCM,data:e0w0G/1EvRe6SoDOS/Ex+8AyQdAROloToIBu9KKpOel5is7NocuA,iv:PlS9wvocjc2Hbmw2CJuO3HATJomU8T0aEuT9JjazxJo=,tag:Pr1p4Ob+T6fwnDLPUISWSA==,type:comment]
#ENC[AES256_GCM,data:ECQiH5qaoAOxTfXjU9KCach35k691KlhQ0d3ekkUBgmf+1vo7CfHos41U5dh5zAkizYpXusQoMI3furR1WnL,iv:37tpmegHZtpaqJI2jQ3HPcYkrvsRZcYEVxph4Ma6gl8=,tag:L/vxJGtVu7sTCamTBfWz7A==,type:comment]
traefik_acme_email: ENC[AES256_GCM,data:Axpg75z2kmPSCuh+jIo0eQ==,iv:mxly4FEv4ov54my0MkM/tRf7hwEXyCRl5wbjGVwqthM=,tag:7RL/OXBeaMN3oGchEoYOMw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG5CS1BZdyAwU3Bu
            U2c0Uml2eWY0Sk42N0V6Sm50TjFsa1pVSmVwYmFqTEYxb0xSaEZZCjEwMmszL0hj
            cHpyNyt5TDRmL1ZuNDhraHlJQTB3MVlaNE9SdHRrcW0ycWcKLS0tIG5BbU44MVJa
            elEwb2o1eCtvRi9yOUx5M3M4TnZIN1piaUJQT2JYcnN2azgKVEG9BHcx26D4GeAZ
            k8kcohd8XENQzgpFEZIsVyq1+7Fn/GK5+Loy2tV3Z60IlehkKg8+KgKnjZjD1cQO
            c8HilA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKFyGuei5gt+jbejZvCrpX0XXD1854N7BkkmEQDRh28/ sops-control-key
    lastmodified: "2026-10-02T14:49:08Z"
    mac: ENC[AES256_GCM,data:zApE0xaV8C8jPYw3hoyIWyQlUjmHP1Jw7TQ+UPU1C5wZi4f8x15iJLq99Iz+u0jiBNOtdpBnxHeTaIxSEa+DScVLu9UC5XpAfPOwCsMiVfU0hWTTKyNdEa7ogQJVvdMBlmv3SztDiWHrf3nTgqrHfPE6E01KcXalLg/KMjbYPcc=,iv:/BJIIqZjwce3T7eAocmH3vL6wGCxdFJ1FilQdI4c9sI=,tag:dKtRu+/2j7IYjHlklmGm3A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
