#ENC[AES256_GCM,data:5I4qeafX5X/k6vpbWDWFUWO9m7nXrjdr7E/rvgMzWuuLWmCHSqop,iv:WtcMEfkPlZGmF8PLgRWRwNPZzPWLRNJHkqlAjjgquWc=,tag:+aFcrO4jwRXmTLPzb7SHGg==,type:comment]
#ENC[AES256_GCM,data:U5Jxc2RrQzpQ1nAc44a8z4hDHhi4CalUxsZWxGFxaxtH5FQwNk4WnCU9YoC+pAekjD+d7J5RyoZ1gc8k+rc+,iv:PK+lTZ5dUltO5g2xk6WXk/0Z/YYP2kQuXsYO+Dz+3sM=,tag:rD9o42YVUbw6dYnjbtsk1A==,type:comment]
traefik_acme_email: ENC[AES256_GCM,data:iZ5sacHego+rJxbTsx3iuQ==,iv:XiYYm1+Jre2lg1TQSrcFDk9gsHSy4sBs95I+fSnj8fE=,tag:XRbE/VLFADKz3jIbzdkNTg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEt0dUtoUSA2L1p2
            UzVuc0R4dE85Y3M5NHhmZDZFUkJoc0JJTTNHWWJEeUV2QmdsakVBCjdacXcrdWRr
            MC9NNzVUT1NsZ203clZHbWJVbzZpRVVEVnVETUttRWRTV3MKLS0tIE15RHp3K0pP
            WGhwTkd1MTV3VTgxT2xsNTBIcTM0T2FFUWpWQXVlT0Z3YUUKYYHLDeRBH9VDRpaS
            ElwrJ3YizsCzxg/hQ3p2tZMyZG8m40ZzKhZ9WfgJii8UpvZc7NXvQQeMKvehNTfS
            k4E9hQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEVkycfAgl4lqaLLqkClUVlaX/ZiSZ+0l0i6rFtuZx/J sops-control-key
    lastmodified: "2026-10-02T13:57:53Z"
    mac: ENC[AES256_GCM,data:DEq+EuSHG+ZtV20DechTPSR0MLXAeXjGGxvLpFi4TAEnqkUY1u/3THLj0HBy/LArPZZBqbES3Fk8Vl79MGYSPQjzH22L0q+15S0Bb6rcLszCIppSk8AfMdT6TxTCXuU2oSlPGt79xC3kKxoHYJx5uyMNrmCgMh71J6aW2J2p5qs=,iv:4fJHmlZE0FJOhY2/akCLJU1GvvIlvaqu5E6jFVJ7UP0=,tag:+CMr8F3795KtuiFMWn0zKQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
