---
all:
  children:
    podman_hosts:
      hosts:
        podman:
          ansible_host: "{{ podman_vm_address }}"
          ansible_user: ansible
          ansible_ssh_private_key_file: "{{ lookup('ansible.builtin.env', 'HOMELAB_SSH_KEY', default=lookup('ansible.builtin.env', 'HOME') ~ '/.ssh/homelab_ed25519') }}"
