---
- name: Install Podman
  ansible.builtin.apt:
    name:
      - podman
      - uidmap
      - slirp4netns
      - fuse-overlayfs
    state: present
    update_cache: true

- name: Enable the Podman API socket
  ansible.builtin.systemd:
    name: podman.socket
    enabled: true
    state: started
