---
- name: Install Podman
  ansible.builtin.apt:
    name:
      - podman
      - uidmap
      - slirp4netns
      - fuse-overlayfs
    state: present
    update_cache: true

- name: Create Quadlet directory
  ansible.builtin.file:
    path: /etc/containers/systemd
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Enable the Podman API socket
  ansible.builtin.systemd:
    name: podman.socket
    enabled: true
    state: started
