#ENC[AES256_GCM,data:VDGteOlnVr5/eoWT8xYJs224u1lHEE6YuA+OK/5+1Dq5dv+Hyt4GK7/5EN8OQ1yqqDA=,iv:KT4BMLuwbNwW43zgX8jOgyqzTgHtkwAJDMZONyrcbwg=,tag:E42wVWO7UBNFLiR7PjcCrQ==,type:comment]
podman_vm_id: ENC[AES256_GCM,data:Fzer,iv:YBuo/Mtnr8Fr2bV07lIbfJ5Q5i25wIhuVttmzZcrpac=,tag:Wj3SF8OQYezyPrwbHUxJOw==,type:int]
podman_vm_name: ENC[AES256_GCM,data:O6LcYy+s,iv:vody5R57VXgSwtdLQRx4kakhE7bjDM7P6kreMs+KQ7Y=,tag:Dhe+FdqsfRA4jmlEoNr1Qg==,type:str]
podman_vm_address: ENC[AES256_GCM,data:VumYjZpFe9QCVw==,iv:/jdc9ptF7CXwcfcfsSo2SXZwhtCjF/NzBo+3I3LHvSo=,tag:Dy8xXeCpAfjW1e/vEZMp+g==,type:str]
podman_vm_cidr: ENC[AES256_GCM,data:+2KOOKJETV0wWdOKaw==,iv:0QCe0ljlRjNQOepESQpaCf3KfM2u+Pxu+CFSOG7hCyQ=,tag:/nA8tMYPmeRQqk7LlKGvPg==,type:str]
podman_vm_gateway: ENC[AES256_GCM,data:EcDA1Sj6o7c3hQ==,iv:TkMnHV2SZWRCji/AvRlTLX4MKeFsrn0PPMXRWUeQZ7w=,tag:JBd3DSiXWBcuNMEkhj9QVw==,type:str]
podman_vm_nameserver: ENC[AES256_GCM,data:Pn6QAGpjfqDzog==,iv:NoF4fbMwaRl+UxtMQJeZdG2MaTp+/dzdph7FeS8kIRg=,tag:89HKpXnZqUnvmuOrEX2jZA==,type:str]
podman_vm_cores: ENC[AES256_GCM,data:9Q==,iv:WNUSauHkXcbAcKRJ30F1diUWG1Fs/8XYs8bk5YA5oiw=,tag:G9XXLXijsCPZEDiFQ2OeqA==,type:int]
podman_vm_memory: ENC[AES256_GCM,data:IZnE9g==,iv:Gs8hOy6F35bloDJioRMdXNtTgCmam6/L+Qz0QFXS3X8=,tag:NueYPc8EptGdpnBMEvE0ig==,type:int]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEt0dUtoUSBuMXNH
            Uk5QR1hGSlRWN215dktNUHd2Z01ZckdhM0dhZnVDdkljZGkrUUhVCmVtTnFXWTli
            QXU3RVlXZjVIMjJ2QVNZVXJFa1hVazlwdDVsK2hrbVRGcG8KLS0tIGI2NWM0WVkv
            OFh4VWQ5MlBVaTJ1d01kdXRrYjQxSHJMeGVZOE5pLzYwOUUKno78RqiL3hL/1FOO
            oiU8WPrjIfKsR1GYucrymcGjm6NiQdBqyHrJpLWmPR6R3oZLScZtAa9Mx4oYDsXx
            CC5/Vg==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEVkycfAgl4lqaLLqkClUVlaX/ZiSZ+0l0i6rFtuZx/J sops-control-key
    lastmodified: "2026-10-02T14:37:07Z"
    mac: ENC[AES256_GCM,data:UsMnMnHYn2TIGPzHhzt2zsODUx0imexWWaS3JCFCKq2yMNn1HUwsUWiHzNiAfymIsOYEG4T5jybq26wsGTTIxNwwQGejyJCafQ09/bsKBSVWJtzs+Ys9pp+uhEBr2JODzYzwD/OidRekP+QAjOz0vj6lH0Z/j0shmcZsg5+ispI=,iv:SzQU1dT1Vc0UTHa4RKY1Sh3OLdszji/BOD3+4eiHQD0=,tag:qsuj5fMncN46nGn+/ARmrA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
