#ENC[AES256_GCM,data:Zv5DLjfJV+YEg/m9j4QDu+nJnePz2Z8YVIlN7Aze43VxTJg5XFN6cMZSLbvfsl2OlWU=,iv:UfP3kXU+z8CkZRrhqso4jPTU8fizXkdEciWVRdEyk0I=,tag:UIUEHwoeQes4h1UatG0flg==,type:comment]
podman_vm_id: ENC[AES256_GCM,data:mwYc,iv:vBffaYsnE7/lsnUqkqYMLRf7e+dfpUzTm4SC5XM6XlQ=,tag:AXeqr/0Mqn18NSXNQxUEXw==,type:int]
podman_vm_name: ENC[AES256_GCM,data:qlPgHIIp,iv:A238IaPu+2bAL/GqOSy/hkoqeLAJoesGIIHN5/IxELU=,tag:WTRjKaFe81nADi4K9ifUWQ==,type:str]
podman_vm_address: ENC[AES256_GCM,data:mmIvT90gLZ0qZw==,iv:+1bHOHqdN0pmIR6G8g9yx4DqLq++68FyGfDsiTlIUC8=,tag:JgGdDI62cmeVWskOWbEizg==,type:str]
podman_vm_cidr: ENC[AES256_GCM,data:FduGosItXSJeRe88/w==,iv:crstEfe3bRJkssYIgS1bFUZGPPSFnPRbuyPHPpNjIgc=,tag:toE8LktKEf+sRzVabau8/w==,type:str]
podman_vm_gateway: ENC[AES256_GCM,data:C4NMsfImUWYH0Q==,iv:NLmKDMarpiP+4+O1ux/+LCCi5XXnJCcDChp2xeWQtpA=,tag:CFl4Nrk5E7ue+Mw039pgfQ==,type:str]
podman_vm_nameserver: ENC[AES256_GCM,data:uQqfqEFmCyiiTg==,iv:6NSawoqwaxZsUp6rrrj0HoqMGsxD2K+XYN9bImHaYjo=,tag:nfYqwWoNp4HIPh9B+N96fQ==,type:str]
podman_vm_cores: ENC[AES256_GCM,data:Vw==,iv:wL07hzZh2Xkfxv84+gRqTqz0jyroxs9aNthcwRswTRg=,tag:ltibHRn707U+nmuu+BMCYQ==,type:float]
podman_vm_memory: ENC[AES256_GCM,data:I++QyA==,iv:hYtis9TtIPgtxXnX5m8Zp6qKgl8aWAevuDpF7JZn8bM=,tag:lW8i26R1zX4dIWfn9+sQyA==,type:int]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG5CS1BZdyBCWm1W
            Wnpoc1BMbGR5RnRwNXlKK1ZVaGVjcGVteXlNZWVQMkpnWXVKY1VzCkZRNSt1bEpT
            WkhqNDRKUEU4Vlh3Qnd5ZjJvRnhmYXVaRUV4N3N1V0tlNUkKLS0tIG9CV2t1ZTBs
            UWc1dStwWUxiRzF0RnQ3ZFd6SmhxMUdUdlVWSU1OQ2xmL00K10ddQ5lPZ2C4PWva
            hgvd6NQm+nnk71vuzlNFIheuc1DbPpBIsCga4e8Jo0MrZaLmDL33GegQBqldvH1j
            VEN46Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKFyGuei5gt+jbejZvCrpX0XXD1854N7BkkmEQDRh28/ sops-control-key
    lastmodified: "2026-10-02T15:45:39Z"
    mac: ENC[AES256_GCM,data:I+XxnyAf+HGpH4yAEYGJYsg7x9F4HyLHgPGR0TJ1OW3C319R9+DGo7Il6cGVgDIQP7wAVYjYjbDfBnqROuUvZV4AOqzJsoYtYlNwRaATq+FupHXFFYzSpwtMeWpPuG2Ns41FjXKoqSjf9IrI0W1sPXPrOXUdE+FtgzMaDznlcDA=,iv:1hfAnFBbXxODe5XKvp6WFxfU1ylRiMcGui455Ybv6Tg=,tag:UEQqE4C4ToBtgbbgL26clg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
