podman_vm_id: 101
podman_vm_name: podman
podman_vm_address: 10.0.0.101
podman_vm_cidr: 10.0.0.101/24
podman_vm_gateway: 10.0.0.1
podman_vm_nameserver: 10.0.0.1
podman_vm_cores: 2
podman_vm_memory: 2048
